/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_vw_wrapper_learner_VWFloatLearner */

#ifndef _Included_com_indeed_vw_wrapper_learner_VWFloatLearner
#define _Included_com_indeed_vw_wrapper_learner_VWFloatLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_indeed_vw_wrapper_learner_VWFloatLearner
 * Method:    predictFloat
 * Signature: (Ljava/lang/String;ZJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_indeed_vw_wrapper_learner_VWFloatLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
