/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_vw_wrapper_learner_VWFloatArrayLearner */

#ifndef _Included_com_indeed_vw_wrapper_learner_VWFloatArrayLearner
#define _Included_com_indeed_vw_wrapper_learner_VWFloatArrayLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_indeed_vw_wrapper_learner_VWFloatArrayLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_indeed_vw_wrapper_learner_VWFloatArrayLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
