/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_vw_wrapper_learner_VWActionScoresLearner */

#ifndef _Included_com_indeed_vw_wrapper_learner_VWActionScoresLearner
#define _Included_com_indeed_vw_wrapper_learner_VWActionScoresLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_indeed_vw_wrapper_learner_VWActionScoresLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)Lcom/indeed/vw/wrapper/learner/ActionScores;
 */
JNIEXPORT jobject JNICALL Java_com_indeed_vw_wrapper_learner_VWActionScoresLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     com_indeed_vw_wrapper_learner_VWActionScoresLearner
 * Method:    predictMultiline
 * Signature: ([Ljava/lang/String;ZJ)Lcom/indeed/vw/wrapper/learner/ActionScores;
 */
JNIEXPORT jobject JNICALL Java_com_indeed_vw_wrapper_learner_VWActionScoresLearner_predictMultiline
(JNIEnv *, jobject, jobjectArray, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
