/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_vw_wrapper_learner_VWLearners */

#ifndef _Included_com_indeed_vw_wrapper_learner_VWLearners
#define _Included_com_indeed_vw_wrapper_learner_VWLearners
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_vw_wrapper_learner_VWLearners
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_vw_wrapper_learner_VWLearners_initialize__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_indeed_vw_wrapper_learner_VWLearners
 * Method:    initialize
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_vw_wrapper_learner_VWLearners_initialize___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_indeed_vw_wrapper_learner_VWLearners
 * Method:    getReturnType
 * Signature: (J)Lcom/indeed/vw/wrapper/learner/VWLearners/VWReturnType;
 */
JNIEXPORT jobject JNICALL Java_com_indeed_vw_wrapper_learner_VWLearners_getReturnType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_indeed_vw_wrapper_learner_VWLearners
 * Method:    closeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_vw_wrapper_learner_VWLearners_closeInstance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
