/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_vw_wrapper_learner_VWIntLearner */

#ifndef _Included_com_indeed_vw_wrapper_learner_VWIntLearner
#define _Included_com_indeed_vw_wrapper_learner_VWIntLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_indeed_vw_wrapper_learner_VWIntLearner
 * Method:    predictFloat
 * Signature: (Ljava/lang/String;ZJ)F
 */
JNIEXPORT jint JNICALL Java_com_indeed_vw_wrapper_learner_VWIntLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
