/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_vw_wrapper_learner_VWIntArrayLearner */

#ifndef _Included_com_indeed_vw_wrapper_learner_VWIntArrayLearner
#define _Included_com_indeed_vw_wrapper_learner_VWIntArrayLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_indeed_vw_wrapper_learner_VWIntArrayLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)[F
 */
JNIEXPORT jintArray JNICALL Java_com_indeed_vw_wrapper_learner_VWIntArrayLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
